export const AccountDITokens = {
  REPOSITORY: Symbol('REPOSITORY'),
  CREATE_USE_CASE: Symbol('CREATE_USE_CASE'),
  FIND_ALL_USE_CASE: Symbol('FIND_ALL_USE_CASE'),
  FIND_BY_EMAIL_USE_CASE: Symbol('FIND_BY_EMAIL_USE_CASE'),
  FIND_BY_ID_USE_CASE: Symbol('FIND_BY_ID_USE_CASE'),
  UPDATE_BY_ID_USE_CASE: Symbol('UPDATE_BY_ID_USE_CASE'),
  DELETE_BY_ID_USE_CASE: Symbol('DELETE_BY_ID_USE_CASE'),
} as const;
