version: '3.8'

services:
  DB:
    image: mysql:8.0.28
    environment:
      MYSQL_DATABASE: 'social_commerce'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - social_commerce:/var/lib/mysql

volumes:
  social_commerce:
